project:
  type: website
  output-dir: docs
  resources:
    - resume/Kehangqin.pdf


website:
  title: "Kehang's Website"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: resume/index.qmd
        text: Resume
      - href: blog.qmd
        text: Projects

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true


