project:
  type: website
  output-dir: docs


website:
  title: "Kehang's Website"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: resume/index.qmd
        text: Resume
      - href: blog.qmd
        text: Projects

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    code-fold: true
    code-tools: true
    code-summary: "Show code"
    toc: true


